openapi: 3.0.0
info:
  title: "Complex API with All Field Types"
  version: "1.0.0"
  description: "A comprehensive API to test AI payload generation for any field type"
servers:
  - url: "https://api.example.com"
paths:
  /complex-user:
    post:
      summary: "Create a complex user with all field types"
      operationId: "createComplexUser"
      tags: ["users"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ["id", "name", "email", "profile", "preferences"]
              properties:
                id:
                  type: string
                  format: uuid
                  example: "123e4567-e89b-12d3-a456-426614174000"
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  format: email
                  example: "john.doe@example.com"
                age:
                  type: integer
                  minimum: 18
                  maximum: 120
                  example: 30
                isActive:
                  type: boolean
                  example: true
                score:
                  type: number
                  format: float
                  minimum: 0.0
                  maximum: 100.0
                  example: 95.5
                birthDate:
                  type: string
                  format: date
                  example: "1990-01-15"
                createdAt:
                  type: string
                  format: date-time
                  example: "2023-01-01T10:30:00Z"
                tags:
                  type: array
                  items:
                    type: string
                  example: ["developer", "admin", "premium"]
                phoneNumbers:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: ["mobile", "home", "work"]
                      number:
                        type: string
                        pattern: "^\\+?[1-9]\\d{1,14}$"
                  example:
                    - type: "mobile"
                      number: "+1234567890"
                    - type: "work"
                      number: "+1987654321"
                address:
                  type: object
                  properties:
                    street:
                      type: string
                      example: "123 Main St"
                    city:
                      type: string
                      example: "New York"
                    state:
                      type: string
                      example: "NY"
                    zipCode:
                      type: string
                      pattern: "^\\d{5}(-\\d{4})?$"
                      example: "10001"
                    country:
                      type: string
                      example: "USA"
                profile:
                  type: object
                  required: ["bio", "avatar"]
                  properties:
                    bio:
                      type: string
                      maxLength: 500
                      example: "Software engineer with 10+ years of experience"
                    avatar:
                      type: string
                      format: uri
                      example: "https://example.com/avatars/john.jpg"
                    socialLinks:
                      type: object
                      properties:
                        twitter:
                          type: string
                          format: uri
                          example: "https://twitter.com/johndoe"
                        linkedin:
                          type: string
                          format: uri
                          example: "https://linkedin.com/in/johndoe"
                        github:
                          type: string
                          format: uri
                          example: "https://github.com/johndoe"
                preferences:
                  type: object
                  properties:
                    theme:
                      type: string
                      enum: ["light", "dark", "auto"]
                      example: "dark"
                    language:
                      type: string
                      enum: ["en", "es", "fr", "de"]
                      example: "en"
                    notifications:
                      type: object
                      properties:
                        email:
                          type: boolean
                          example: true
                        push:
                          type: boolean
                          example: false
                        sms:
                          type: boolean
                          example: true
                    timezone:
                      type: string
                      example: "America/New_York"
                metadata:
                  type: object
                  additionalProperties: true
                  example:
                    lastLogin: "2023-12-01T15:30:00Z"
                    loginCount: 150
                    customField: "custom value"
      responses:
        "201":
          description: "Complex user created successfully"

  /nested-orders:
    post:
      summary: "Create a complex order with nested structures"
      operationId: "createNestedOrder"
      tags: ["orders"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ["orderId", "customer", "items", "shipping"]
              properties:
                orderId:
                  type: string
                  pattern: "^ORD-\\d{8}-\\d{4}$"
                  example: "ORD-20231201-1234"
                customer:
                  type: object
                  required: ["id", "name", "email"]
                  properties:
                    id:
                      type: string
                      format: uuid
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    name:
                      type: string
                      example: "Jane Smith"
                    email:
                      type: string
                      format: email
                      example: "jane.smith@example.com"
                    phone:
                      type: string
                      example: "+1987654321"
                items:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required: ["productId", "quantity", "price"]
                    properties:
                      productId:
                        type: string
                        example: "PROD-001"
                      name:
                        type: string
                        example: "iPhone 15 Pro"
                      quantity:
                        type: integer
                        minimum: 1
                        example: 2
                      price:
                        type: number
                        format: float
                        minimum: 0.01
                        example: 999.99
                      options:
                        type: object
                        properties:
                          color:
                            type: string
                            enum: ["black", "white", "blue", "red"]
                            example: "black"
                          storage:
                            type: string
                            enum: ["128GB", "256GB", "512GB", "1TB"]
                            example: "256GB"
                          warranty:
                            type: boolean
                            example: true
                shipping:
                  type: object
                  required: ["address", "method"]
                  properties:
                    address:
                      type: object
                      required: ["street", "city", "state", "zipCode"]
                      properties:
                        street:
                          type: string
                          example: "456 Oak Ave"
                        city:
                          type: string
                          example: "Los Angeles"
                        state:
                          type: string
                          example: "CA"
                        zipCode:
                          type: string
                          example: "90210"
                        country:
                          type: string
                          example: "USA"
                    method:
                      type: string
                      enum: ["standard", "express", "overnight"]
                      example: "express"
                    trackingNumber:
                      type: string
                      example: "1Z999AA1234567890"
                payment:
                  type: object
                  required: ["method", "amount"]
                  properties:
                    method:
                      type: string
                      enum: ["credit_card", "paypal", "apple_pay", "google_pay"]
                      example: "credit_card"
                    amount:
                      type: number
                      format: float
                      minimum: 0.01
                      example: 1999.98
                    currency:
                      type: string
                      pattern: "^[A-Z]{3}$"
                      example: "USD"
                    cardDetails:
                      type: object
                      properties:
                        last4:
                          type: string
                          pattern: "^\\d{4}$"
                          example: "1234"
                        brand:
                          type: string
                          enum: ["visa", "mastercard", "amex", "discover"]
                          example: "visa"
                        expiryMonth:
                          type: integer
                          minimum: 1
                          maximum: 12
                          example: 12
                        expiryYear:
                          type: integer
                          minimum: 2024
                          example: 2028
                status:
                  type: string
                  enum:
                    [
                      "pending",
                      "confirmed",
                      "shipped",
                      "delivered",
                      "cancelled",
                    ]
                  example: "pending"
                notes:
                  type: array
                  items:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                        example: "2023-12-01T10:30:00Z"
                      message:
                        type: string
                        example: "Customer requested express shipping"
                      author:
                        type: string
                        example: "sales@example.com"
      responses:
        "201":
          description: "Complex order created successfully"

  /file-upload:
    post:
      summary: "Upload file with metadata"
      operationId: "uploadFile"
      tags: ["files"]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: ["file", "metadata"]
              properties:
                file:
                  type: string
                  format: binary
                  description: "File to upload"
                metadata:
                  type: object
                  required: ["filename", "type", "size"]
                  properties:
                    filename:
                      type: string
                      example: "document.pdf"
                    type:
                      type: string
                      enum: ["image", "document", "video", "audio"]
                      example: "document"
                    size:
                      type: integer
                      minimum: 1
                      example: 1048576
                    description:
                      type: string
                      example: "Important business document"
                    tags:
                      type: array
                      items:
                        type: string
                      example: ["business", "important", "confidential"]
                    permissions:
                      type: object
                      properties:
                        public:
                          type: boolean
                          example: false
                        allowDownload:
                          type: boolean
                          example: true
                        allowShare:
                          type: boolean
                          example: false
      responses:
        "201":
          description: "File uploaded successfully"

components:
  schemas:
    ComplexObject:
      type: object
      properties:
        id:
          type: string
          format: uuid
        data:
          type: object
          additionalProperties: true
        arrays:
          type: array
          items:
            type: object
            properties:
              nested:
                type: object
                properties:
                  deep:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        count:
                          type: integer
                        active:
                          type: boolean
